---
controller_templates:
  - name: Applications / Install Apache
    project: Git Repo
    playbook: apache_install.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
