---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  vars:
    controller_validate_certs: false
  collections:
    - awx.awx
  
  - name: Project Foo
    controller_projects:
      name: "Foo"
      description: "Foo bar project"
      organization: "test"
      state: present
      controller_config_file: "~/tower_cli.cfg"
