---
- name: Exlude Packages in yum.conf
  hosts: all
  tasks: 
    - name: Add exclusions in yum.conf
      blockinfile:
        path: /etc/yum.conf
        insertafter: '[main]'
        block: |
          cachedir=/var/cache/yum/$basearch/$releasever
          keepcache=0
          debuglevel=2
          logfile=/var/log/yum.log
          exclude=kernel* redhat-release* gcc*
