---
- name: Remove Apache Server
  hosts: web
  become: yes
  tasks:

  - name: remove Apache packages
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - httpd
      - httpd-tools

  - name: remove index.html
    file:
      path: /var/www/html/index.html
      state: absent
      force: yes
    ignore_errors: True
