---

- name: update package 
  hosts: all
  become: true
  tasks:
    - name: update list of packages
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - kernel
        - kernel-modules

    - name: reboot the machine
      reboot:

