---
- hosts: windows
  name: Removing IIS Feature
  tasks:
    - name: Remove IIS
      win_feature:
        name: Web-Server
        state: absent
        
    - name: Remove index.html file
      win_file:
        path: C:\Inetpub\wwwroot\index.html
        state: absent       
