---
- name: Install Specific Packages using Chocolatey with Survey
  hosts: windows
  gather_facts: false

  tasks:
  - name: Installing sequentially
    win_chocolatey:
      name: "{{ choco_packages }}"
      state: latest
