---
- name: Install Specific versions of packages using Chocolatey
  hosts: all
  gather_facts: false
  vars:
    choco_packages:
      - name: googlechrome
        version: 101.0.4951.64
      - name: python
        version: 3.6.0
  tasks:
  - name: Install specific versions of packages sequentially
    win_chocolatey:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    loop: "{{ choco_packages }}"

  - name: Check python version
    win_command: python --version
    register: check_python_version

  - name: Check Google Chrome version
    win_command: googlechrome --version
    register: check_chrome_version

  - debug:
      msg: Python Version is {{ check_python_version.stdout_lines[0] }} and Chrome version is {{ check_chome_version.stdout_lines[0] }}
