---
- name: Install Specific Packages using Chocolatey with Survey
  hosts: all
  gather_facts: false

  tasks:
  - name: Installing the selected packages
    win_chocolatey:
      name: "{{ choco_packages }}"
      state: latest
