---
- name: Ensure that the httpd package is installed
  yum:
    name: httpd
    state: present
  notify: apache-restart

- name: latest firewalld version installed
  yum:
    name: firewalld
    state: latest

- name: firewalld enabled and running
  service:
    name: firewalld
    enabled: true
    state: started

- name: firewalld permits http service
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes

- name: Apache enabled and running
  service:
    name: httpd
    enabled: true
    state: started
